// Common Type
export const API_LOADING = 'API_LOADING';
export const OPERATION_FAILED = 'OPERATION_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
